# Generated by Django 4.2.20 on 2025-04-29 00:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("commitfest", "0010_add_failing_since_column"),
    ]
    operations = [
        migrations.AlterModelOptions(
            name="mailthreadattachment",
            options={
                "ordering": (
                    "-date",
                    "messageid",
                    "ispatch",
                    "filename",
                    "attachmentid",
                )
            },
        ),
        migrations.AlterUniqueTogether(
            name="mailthreadattachment",
            unique_together={("mailthread", "messageid", "attachmentid")},
        ),
        migrations.AddField(
            model_name="mailthreadattachment",
            name="contenttype",
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="patch",
            name="patchset_messagedate",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="patch",
            name="patchset_messageid",
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="mailthread",
            name="patchsetmsgid",
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
