# Generated by Django 4.2.20 on 2025-04-29 00:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("commitfest", "0011_accept_multiple_attachments"),
    ]

    operations = [
        migrations.CreateModel(
            name="CfbotQueue",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("current_queue_item", models.IntegerField(blank=True, null=True)),
                ("weight", models.IntegerField(default=1, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name="CfbotQueueItem",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("patch_id", models.IntegerField()),
                ("message_id", models.TextField()),
                ("ignore_date", models.DateTimeField(blank=True, null=True)),
                ("processed_date", models.DateTimeField(blank=True, null=True)),
                ("ll_prev", models.IntegerField(null=True)),
                ("ll_next", models.IntegerField(null=True)),
                ("last_base_commit_sha", models.TextField(null=True)),
                (
                    "queue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="commitfest.cfbotqueue",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="cfbotqueue",
            constraint=models.UniqueConstraint(
                condition=models.Q(("id__isnull", False)),
                fields=("weight",),
                name="unique_single_cfbot_queue",
            ),
        ),
        migrations.AddConstraint(
            model_name="cfbotqueue",
            constraint=models.CheckConstraint(
                check=models.Q(("weight", 1)), name="check_weight_equals_one"
            ),
        ),
        migrations.AddConstraint(
            model_name="cfbotqueueitem",
            constraint=models.UniqueConstraint(
                fields=("patch_id",), name="unique_patch_id"
            ),
        ),
    ]
