# Generated by Django 4.2.20 on 2025-04-29 01:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("commitfest", "0012_cfbotqueue_cfbotqueueitem_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CfbotBranchHistory",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("patch_id", models.IntegerField()),
                ("branch_id", models.IntegerField()),
                ("branch_name", models.TextField()),
                ("commit_id", models.TextField(blank=True, null=True)),
                ("apply_url", models.TextField()),
                ("status", models.TextField()),
                ("needs_rebase_since", models.DateTimeField(blank=True, null=True)),
                ("failing_since", models.DateTimeField(blank=True, null=True)),
                ("created", models.DateTimeField()),
                ("modified", models.DateTimeField()),
                ("version", models.TextField(blank=True, null=True)),
                ("patch_count", models.IntegerField(blank=True, null=True)),
                ("first_additions", models.IntegerField(blank=True, null=True)),
                ("first_deletions", models.IntegerField(blank=True, null=True)),
                ("all_additions", models.IntegerField(blank=True, null=True)),
                ("all_deletions", models.IntegerField(blank=True, null=True)),
                ("task_count", models.IntegerField(blank=True, null=True)),
                ("base_commit_sha", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name_plural": "Cfbot Branch Histories",
                "ordering": ("-modified",),
            },
        ),
        migrations.AddField(
            model_name="cfbottask",
            name="payload",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cfbotbranch',
            name='base_commit_sha',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="cfbotbranch",
            name="status",
            field=models.CharField(max_length=100, null=False),
        ),
        migrations.AlterField(
            model_name="cfbottask",
            name="status",
            field=models.TextField(
                choices=[
                    ("CREATED", "Created"),
                    ("NEEDS_APPROVAL", "Needs Approval"),
                    ("TRIGGERED", "Triggered"),
                    ("EXECUTING", "Executing"),
                    ("FAILED", "Failed"),
                    ("COMPLETED", "Completed"),
                    ("SCHEDULED", "Scheduled"),
                    ("ABORTED", "Aborted"),
                    ("ERRORED", "Errored"),
                    ("IGNORED", "Ignored"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="cfbottask",
            name="task_id",
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name="CfbotTaskCommand",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
                ("status", models.TextField()),
                ("type", models.TextField()),
                ("duration", models.IntegerField(null=True)),
                ("log", models.TextField(blank=True, null=True)),
                ("payload", models.JSONField(blank=True, null=True)),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="commitfest.cfbottask",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CfbotTaskArtifact",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
                ("path", models.TextField()),
                ("size", models.IntegerField()),
                ("body", models.TextField(blank=True, null=True)),
                ("payload", models.JSONField(blank=True, null=True)),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="commitfest.cfbottask",
                    ),
                ),
            ],
        ),
        migrations.RunSQL(
            """
            CREATE TABLE commitfest_cfbotbranchhistorytask (
                history_id bigint
                    PRIMARY KEY
                    REFERENCES commitfest_cfbotbranchhistory (id)
                        ON DELETE CASCADE,
                branch_tasks jsonb NOT NULL
            );
            """,
            """
            DROP TABLE commitfest_cfbotbranchhistorytask;
            """,
        ),
    ]
