# Generated by Django 4.2.20 on 2025-04-17 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commitfest', '0013_no_patches_in_future_cfs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterModelOptions(
            name='mailthreadattachment',
            options={'ordering': ('-date', 'attachmentid')},
        ),
        migrations.AlterField(
            model_name='commitfest',
            name='status',
            field=models.IntegerField(choices=[(1, 'Future'), (2, 'Open'), (3, 'In Progress'), (4, 'Closed'), (5, 'Drafts')], default=1),
        ),
        migrations.AlterUniqueTogether(
            name='mailthreadattachment',
            unique_together={('mailthread', 'messageid', 'attachmentid')},
        ),
    ]
