# Generated by Django 4.2.20 on 2025-04-17 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commitfest', '0014_workflow_alter_mailthreadattachment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailthread',
            name='patchsetmsgid',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='patch',
            name='patchset_messagedate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patch',
            name='patchset_messageid',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
