# Generated by Django 4.2.20 on 2025-04-17 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commitfest', '0015_mailthread_patchsetmsgid_patch_patchset_messagedate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailthreadattachment',
            name='contenttype',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
