# Generated by Django 4.2.20 on 2025-04-17 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commitfest', '0016_mailthreadattachment_contenttype'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailthreadattachment',
            options={'ordering': ('-date', 'messageid', 'ispatch', 'filename', 'attachmentid')},
        ),
    ]
