# Generated by Django 4.2.20 on 2025-04-17 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commitfest', '0018_cfbotqueue_cfbotqueueitem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cfbotqueueitem',
            name='queue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='commitfest.cfbotqueue'),
        ),
    ]
