# Generated by Django 4.2.20 on 2025-04-19 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commitfest', '0019_alter_cfbotqueueitem_queue'),
    ]

    operations = [
        migrations.CreateModel(
            name='CfbotBranchHistory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('patch_id', models.IntegerField()),
                ('branch_id', models.IntegerField()),
                ('branch_name', models.TextField()),
                ('commit_id', models.TextField(blank=True, null=True)),
                ('apply_url', models.TextField()),
                ('status', models.TextField()),
                ('needs_rebase_since', models.DateTimeField(blank=True, null=True)),
                ('failing_since', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField()),
                ('modified', models.DateTimeField()),
                ('version', models.TextField(blank=True, null=True)),
                ('patch_count', models.IntegerField(blank=True, null=True)),
                ('first_additions', models.IntegerField(blank=True, null=True)),
                ('first_deletions', models.IntegerField(blank=True, null=True)),
                ('all_additions', models.IntegerField(blank=True, null=True)),
                ('all_deletions', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Cfbot Branch Histories',
                'ordering': ('-modified',),
            },
        ),
    ]
