# Generated by Django 4.2.20 on 2025-04-19 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commitfest', '0020_cfbotbranchhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cfbotbranch',
            name='status',
            field=models.TextField(choices=[('new', 'New'), ('testing', 'Testing'), ('finished', 'Finished'), ('failed', 'Failed'), ('timeout', 'Timeout')]),
        ),
        migrations.RunSQL(
            """
            ALTER TYPE cfbotbranch_status
                ADD VALUE 'new'
                BEFORE 'testing';
            """
        ),
    ]
