# Generated by Django 4.2.20 on 2025-04-19 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commitfest', '0021_alter_cfbotbranch_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cfbotbranch',
            name='status',
            field=models.TextField(),
        ),
        # Alter table commitfest_cfbotbranch alter column status type text;
    ]
