# Generated by Django 4.2.20 on 2025-04-19 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commitfest', '0022_alter_cfbotbranch_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cfbotbranchhistory',
            name='task_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.RunSQL(
            """
            CREATE TABLE commitfest_cfbotbranchhistorytask (
                history_id bigint PRIMARY KEY REFERENCES commitfest_cfbotbranchhistory (id) ON DELETE CASCADE,
                branch_tasks jsonb NOT NULL
            );
            """
        ),
    ]
