# Generated by Django 4.2.20 on 2025-04-20 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commitfest', '0025_cfbotbranch_base_commit_sha'),
    ]

    operations = [
        migrations.AddField(
            model_name='cfbotbranchhistory',
            name='base_commit_sha',
            field=models.TextField(blank=True, null=True),
        ),
    ]
