# Generated by Django 4.2.20 on 2025-04-20 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commitfest', '0026_cfbotbranchhistory_base_commit_sha'),
    ]

    operations = [
        migrations.AddField(
            model_name='cfbottask',
            name='payload',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
