# Generated by Django 4.2.20 on 2025-04-20 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commitfest', '0027_cfbottask_payload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cfbottask',
            name='task_id',
            field=models.TextField(),
        ),
    ]
