# Generated by Django 4.2.20 on 2025-04-22 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commitfest', '0028_alter_cfbottask_task_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cfbottask',
            name='status',
            field=models.TextField(choices=[('CREATED', 'Created'), ('NEEDS_APPROVAL', 'Needs Approval'), ('TRIGGERED', 'Triggered'), ('EXECUTING', 'Executing'), ('FAILED', 'Failed'), ('COMPLETED', 'Completed'), ('SCHEDULED', 'Scheduled'), ('ABORTED', 'Aborted'), ('ERRORED', 'Errored'), ('IGNORED', 'Ignored')]),
        ),
        migrations.RunSQL(
            """
            ALTER TYPE cfbottask_status
                ADD VALUE 'IGNORED'
                AFTER 'ERRORED';
            """
        ),
    ]
