# Generated by Django 4.2.20 on 2025-04-25 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commitfest', '0029_alter_cfbottask_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CfbotTaskArtifact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('path', models.TextField()),
                ('size', models.IntegerField()),
                ('body', models.TextField(blank=True, null=True)),
                ('payload', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CfbotTaskCommand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('status', models.TextField()),
                ('type', models.TextField()),
                ('duration', models.IntegerField()),
                ('log', models.TextField(blank=True, null=True)),
                ('payload', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='cfbottaskcommand',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commitfest.cfbottask'),
        ),
        migrations.AddField(
            model_name='cfbottaskartifact',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commitfest.cfbottask'),
        ),
    ]
