# Generated by Django 4.2.20 on 2025-04-26 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commitfest', '0030_cfbottaskartifact_cfbottaskcommand_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Workflow',
        ),
        migrations.AlterField(
            model_name='cfbottaskcommand',
            name='duration',
            field=models.IntegerField(null=True),
        ),
    ]
